name: Trigger auto deployment for tdtommy

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/tdtommy-AutoDeployTrigger-b86f6cac-1c97-427b-aa28-e0588edfdc7b.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.TDTOMMY_REGISTRY_USERNAME }}
          password: ${{ secrets.TDTOMMY_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/tdtommy:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TDTOMMY_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n tdtommy -g discordbots --server ghcr.io --username  ${{ secrets.TDTOMMY_REGISTRY_USERNAME }} --password ${{ secrets.TDTOMMY_REGISTRY_PASSWORD }}
            az containerapp update -n tdtommy -g discordbots --image ghcr.io/tdtommy:${{ github.sha }}
